from enum import Enum


class EventType(Enum):
    CREATE_ISSUE = 1
    UPDATE_ISSUE = 2
    ADD_COMMENT = 3
    DELETE_ISSUE = 4
    CREATE_WIKI = 5
    UPDATE_WIKI = 6
    DELETE_WIKI = 7
    CREATE_ATTACHMENT = 8
    UPDATE_ATTACHMENT = 9
    DELETE_ATTACHMENT = 10
    COMMIT_SUBVERSION = 11
    PUSH_GIT = 12
    CREATE_GIT = 13
    BULK_UPDATE_ISSUE = 14
    JOIN_PROJECT = 15
    LEAVE_PROJECT = 16
    ADD_NOFICATION = 17
    CREATE_PULL_REQUEST = 18
    UPDATE_PULL_REQUEST = 19
    COMMENT_PULL_REQUEST = 20
    DELETE_PULL_REQUEST = 21
    CREATE_MILESTONE = 22
    UPDATE_MILESTONE = 23
    DELETE_MILESTONE = 24
